CREATE DATABASE IF NOT EXISTS wordpress;
USE wordpress;
CREATE USER IF NOT EXISTS 'eryilmaz'@'%' IDENTIFIED BY 'ulus7474';
GRANT ALL PRIVILEGES ON wordpress.* TO 'eryilmaz'@'%';
GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' IDENTIFIED BY 'ulus7474' WITH GRANT OPTION;
FLUSH PRIVILEGES;
